AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  Infrastructure as code for authorization layer (Amazon Verified Permissions and Cedar policies).

Resources:

  PolicyStore:
    Type: AWS::VerifiedPermissions::PolicyStore
    Properties:
      Schema:
        CedarJson: |
          {
          }
      ValidationSettings:
        Mode: STRICT

  PolicyStoreIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /bookstore-demo-app-with-authz/authorization/policy-store-id
      Value: !Ref PolicyStore

Outputs:

  PolicyStoreId:
    Description: "Identifier of the Amazon Verified Permissions policy store."
    Value: !Ref PolicyStore
