AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  Infrastructure as code for authorization layer (Amazon Verified Permissions and Cedar policies).

Resources:

  PolicyStore:
    Type: AWS::VerifiedPermissions::PolicyStore
    Properties:
      Description: Final version of the Cedar policy store that will be recreated independently.
      ValidationSettings:
        Mode: STRICT
      Schema:
        CedarJson: |
          {
            "Bookstore": {
              "actions": {
                "View": {
                  "appliesTo": {
                    "resourceTypes": [
                      "Book"
                    ],
                    "context": {
                      "type": "Record",
                      "attributes": {
                        "region": {
                          "required": true,
                          "name": "region",
                          "type": "String"
                        }
                      }
                    },
                    "principalTypes": [
                      "User"
                    ]
                  },
                  "memberOf": []
                },
                "ViewWithPremiumOffers": {
                  "appliesTo": {
                    "principalTypes": [
                      "User"
                    ],
                    "context": {
                      "type": "Record",
                      "attributes": {
                        "region": {
                          "required": true,
                          "type": "String",
                          "name": "region"
                        }
                      }
                    },
                    "resourceTypes": [
                      "Book"
                    ]
                  },
                  "memberOf": []
                }
              },
              "entityTypes": {
                "Role": {
                  "memberOfTypes": [],
                  "shape": {
                    "type": "Record",
                    "attributes": {}
                  }
                },
                "User": {
                  "memberOfTypes": [
                    "Role"
                  ],
                  "shape": {
                    "type": "Record",
                    "attributes": {
                      "yearsAsMember": {
                        "type": "Long",
                        "required": false
                      }
                    }
                  }
                },
                "Book": {
                  "memberOfTypes": [],
                  "shape": {
                    "attributes": {
                      "owner": {
                        "type": "Entity",
                        "required": true,
                        "name": "User"
                      }
                    },
                    "type": "Record"
                  }
                }
              }
            }
          }


  PolicyStoreIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /bookstore-demo-app-with-authz/authorization/policy-store-id
      Value: !Ref PolicyStore

Outputs:

  PolicyStoreId:
    Description: "Identifier of the Amazon Verified Permissions policy store."
    Value: !Ref PolicyStore
